increase the volume of traces for deserialization benchmarks
DataDog/libdatadog pull request #732
Opened 2024-11-12 21:11 UTC by ekump

# What does this PR do?

Previously, we were performing benchmarks for msgpack deserialization on 2 spans which is both unrealistic, and contributed to variance in benchmarks. This PR changes the payload to approximately 10mb of data (~40k spans). 

# Additional Notes

The benchmark report for this PR can be ignored since the baseline was for just 2 spans.

2024-11-12 21:35 UTC, ajgajg1134 commented on trace-utils/benches/deserialization.rs
> +    let root_span_id = 100000000000 + (trace_id % 1000000);
nit
```suggestion
    let root_span_id = 100_000_000_000 + (trace_id % 1_000_000);
```

2024-11-12 21:35 UTC, ajgajg1134 commented on trace-utils/benches/deserialization.rs
> +        let trace_id = 100000000000 + i as u64;
nit
```suggestion
        let trace_id = 100_000_000_000 + i as u64;
```

2024-11-12 22:00 UTC, ajgajg1134 approved these changes

2024-11-13 07:18 UTC, bantonsson requested changes
So the fact that you've massively increased the data we are deserializing, and there were no measurement changes even though the test doesn't measure per chunk or per span made me suspicious, and the test is now flagged as _unstable_ and excluded. I don't like that the comparison doesn't show which tests are _unstable_. I'll post info on how to look at the raw results in slack.

2024-11-13 08:23 UTC, bantonsson approved these changes
I ran the benchmark twice with this branch as the base, and it was marked as stable and had no performance changes.

2024-11-13 14:32 UTC, merged